language: java
sudo: false
cache:
  directories:
    - $HOME/.m2
script:
  - set -e
  - mvn -version
  - mvn clean
  - mvn clean install --errors --batch-mode
env:
  global:
    - MAVEN_OPTS="-Xmx256m"
    - JAVA_OPTS="-Xmx256m"
jdk:
  - oraclejdk11
after_success:
  - "bash <(curl -s https://codecov.io/bash)"
